// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXCWyK70QMNYwJgLncVPKoMRFu1t4pv8',
    authDomain: 'road-complaint-syste.firebaseapp.com',
    projectId: 'road-complaint-syste',
    storageBucket: 'road-complaint-syste.firebasestorage.app',
    messagingSenderId: '868817718139',
    appId: '1:868817718139:web:364bc3b3f9d9b224028bde',
    measurementId: 'G-32E6VF96NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFaCjP_IVG2kO80KiWoxQBav4XmRukTo',
    appId: '1:868817718139:android:28ffab29812a857b028bde',
    messagingSenderId: '868817718139',
    projectId: 'road-complaint-syste',
    storageBucket: 'road-complaint-syste.firebasestorage.app',
  );
}